### ISSUE TITLE
无效的数值参数“/Wno-register

### ISSUE THREAD

**Issue by hdfuCof** [LUORANCHENG/novel2video#1]
执行pip install soundfile nemo_text_processing gradio WeTextProcessing出现了cl: 命令行 error D8021 :无效的数值参数“/Wno-register”
      error: command 'E:\\VisualStudio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2问题

**Comment by LUORANCHENG** [comment]
> 执行pip install soundfile nemo_text_processing gradio WeTextProcessing出现了cl: 命令行 error D8021 :无效的数值参数“/Wno-register”
>       error: command 'E:\\VisualStudio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.42.34433\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2问题
>       
>       
>       

貌似是在使用VisualStudio进行编译的时候报错，尝试通过conda来安装试一下
```conda install -c conda-forge 安装包名```

**Comment by hdfuCof** [comment]
这个已解决，貌似得安装2.1.6版本的conda install -c conda-forge pynini=2.1.6
