### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrator/.cache/huggingface\\hub/models--2Noise--ChatTTS/snapshots\\1a3c04a8b0651689bd9242fbb55b1f4b5a9aef84\\asset/GPT.pt'

### ISSUE THREAD

**Issue by hdfuCof** [LUORANCHENG/novel2video#2]
![image](https://github.com/user-attachments/assets/89911d0a-2149-4ca3-9c6f-c0dae826ab86)
作者你好，我运行Chattts_test.py出现了这个错误，是哪里配置没配置好嘛

**Comment by xiaofu2475** [comment]
已解决
原因：应该是我第一次下载的时候中断，之后下载出现的问题
解决方法：删除.cahce底下的缓存重新下载
