### ISSUE TITLE
openai连接失败Connection error

### ISSUE THREAD

**Issue by hdfuCof** [LUORANCHENG/novel2video#3]
![image](https://github.com/user-attachments/assets/4e203a91-980a-4157-a659-d3a64b999da3)
![image](https://github.com/user-attachments/assets/467ddaa9-117c-492d-aec4-1e2ac4c2b402)
开启了魔法api key也是有的，但是还是connection error
作者是怎么连接上的，求助

**Comment by LUORANCHENG** [comment]
尝试使用clash的全局模式试一下

**Comment by xiaofu2475** [comment]
可以了，感谢作者

**Comment by elarbor** [comment]
@LUORANCHENG 希望作者可以打包好[releases](https://github.com/LUORANCHENG/novel2video/releases)
